### ISSUE TITLE
转换后生成新文件

### ISSUE THREAD

**Issue by Qukoyk** [Sofronio/YouTubeVTT2ASS#1]
谢谢soso！很棒的工具！
我注意到现在转换后会直接替换VTT内的内容，而且后缀名也依然是VTT。
能否做成转换后保留原有VTT文件并生成新的ass文件？
谢谢！

**Comment by Sofronio** [comment]
本来是写成生成新文件的，但貌似判断加的位置不对。有时间改掉。另外最近vtt格式升级了，需要重构一下程序，否则没法用。

**Comment by Sofronio** [comment]
新版已经修复
